"""empty message

Revision ID: 032b1b2ccb94
Revises: 38d82987e1be
Create Date: 2022-03-25 20:00:57.788644

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '032b1b2ccb94'
down_revision = '38d82987e1be'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
