"""add foreign keys

Revision ID: 5b4d18ac76db
Revises: 570cf3966e04
Create Date: 2022-03-23 23:27:17.246927

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5b4d18ac76db'
down_revision = '570cf3966e04'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('address', sa.Column('person_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'address', 'person', ['person_id'], ['id'])
    op.add_column('nfe', sa.Column('provider_id', sa.Integer(), nullable=True))
    op.add_column('nfe', sa.Column('client_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'nfe', 'person', ['client_id'], ['id'])
    op.create_foreign_key(None, 'nfe', 'person', ['provider_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'nfe', type_='foreignkey')
    op.drop_constraint(None, 'nfe', type_='foreignkey')
    op.drop_column('nfe', 'client_id')
    op.drop_column('nfe', 'provider_id')
    op.drop_constraint(None, 'address', type_='foreignkey')
    op.drop_column('address', 'person_id')
    # ### end Alembic commands ###
