"""add foreign keys

Revision ID: 7d62916965c2
Revises: 5b4d18ac76db
Create Date: 2022-03-23 23:30:44.243322

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7d62916965c2'
down_revision = '5b4d18ac76db'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('address', sa.Column('fk_person_address', sa.Integer(), nullable=True))
    op.drop_constraint('address_person_id_fkey', 'address', type_='foreignkey')
    op.create_foreign_key(None, 'address', 'person', ['fk_person_address'], ['id'])
    op.drop_column('address', 'person_id')
    op.add_column('nfe', sa.Column('fk_person_provider_nfe', sa.Integer(), nullable=True))
    op.add_column('nfe', sa.Column('fk_person_client_nfe', sa.Integer(), nullable=True))
    op.drop_constraint('nfe_client_id_fkey', 'nfe', type_='foreignkey')
    op.drop_constraint('nfe_provider_id_fkey', 'nfe', type_='foreignkey')
    op.create_foreign_key(None, 'nfe', 'person', ['fk_person_provider_nfe'], ['id'])
    op.create_foreign_key(None, 'nfe', 'person', ['fk_person_client_nfe'], ['id'])
    op.drop_column('nfe', 'client_id')
    op.drop_column('nfe', 'provider_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('nfe', sa.Column('provider_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('nfe', sa.Column('client_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'nfe', type_='foreignkey')
    op.drop_constraint(None, 'nfe', type_='foreignkey')
    op.create_foreign_key('nfe_provider_id_fkey', 'nfe', 'person', ['provider_id'], ['id'])
    op.create_foreign_key('nfe_client_id_fkey', 'nfe', 'person', ['client_id'], ['id'])
    op.drop_column('nfe', 'fk_person_client_nfe')
    op.drop_column('nfe', 'fk_person_provider_nfe')
    op.add_column('address', sa.Column('person_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'address', type_='foreignkey')
    op.create_foreign_key('address_person_id_fkey', 'address', 'person', ['person_id'], ['id'])
    op.drop_column('address', 'fk_person_address')
    # ### end Alembic commands ###
