"""change type of number address

Revision ID: 80e3748ea764
Revises: f5e514501f81
Create Date: 2022-03-24 00:39:41.783390

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '80e3748ea764'
down_revision = 'f5e514501f81'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
