"""change type of NFE_id to String

Revision ID: a4f528912c3b
Revises: 80e3748ea764
Create Date: 2022-03-24 00:58:54.747976

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a4f528912c3b'
down_revision = '80e3748ea764'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
