"""add foreign keys

Revision ID: f5e514501f81
Revises: 7d62916965c2
Create Date: 2022-03-24 00:25:39.650156

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f5e514501f81'
down_revision = '7d62916965c2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'nfe', ['nfe_id'])
    op.create_unique_constraint(None, 'person', ['cnpj'])
    op.create_unique_constraint(None, 'person', ['cpf'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'person', type_='unique')
    op.drop_constraint(None, 'person', type_='unique')
    op.drop_constraint(None, 'nfe', type_='unique')
    # ### end Alembic commands ###
