# Generated by Django 5.0.3 on 2024-03-09 18:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notafiscal', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='boleto',
            name='fornecedor',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='fornecedor',
        ),
        migrations.RemoveField(
            model_name='notafiscal',
            name='boletos',
        ),
        migrations.RemoveField(
            model_name='notafiscal',
            name='clientes',
        ),
        migrations.AddField(
            model_name='boleto',
            name='nota_fiscal',
            field=models.ForeignKey(default=-2015, on_delete=django.db.models.deletion.CASCADE, to='notafiscal.notafiscal'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cliente',
            name='nota_fiscal',
            field=models.ForeignKey(default=-1995, on_delete=django.db.models.deletion.CASCADE, to='notafiscal.notafiscal'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cliente',
            name='tipo_documento',
            field=models.CharField(choices=[('CPF', 'CPF'), ('CNPJ', 'CNPJ')], default=-1995, max_length=4),
            preserve_default=False,
        ),
    ]
