# Generated by Django 5.0.3 on 2024-03-09 18:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notafiscal', '0002_remove_boleto_fornecedor_remove_cliente_fornecedor_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cliente',
            old_name='identificador',
            new_name='documento',
        ),
    ]
