# Generated by Django 5.0.3 on 2024-03-10 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notafiscal', '0003_rename_identificador_cliente_documento'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cliente',
            name='nota_fiscal',
        ),
        migrations.AddField(
            model_name='notafiscal',
            name='clientes',
            field=models.ManyToManyField(related_name='notas_fiscais', to='notafiscal.cliente'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='documento',
            field=models.CharField(max_length=14, unique=True),
        ),
        migrations.AlterField(
            model_name='fornecedor',
            name='cnpj',
            field=models.CharField(max_length=14, unique=True),
        ),
    ]
